# Generated by Django 5.0.6 on 2026-05-30 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('mp4', 'Video (MP4)'), ('youtube', 'YouTube Link'), ('link', 'External Link'), ('markdown', 'Markdown / Notes')], max_length=20)),
                ('file_url', models.URLField()),
                ('file_size_mb', models.FloatField(default=0.0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.chapter')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
